random_seed: 444

dataset:
  type: &dataset_type 'Mono3DRefer'
  root_dir: '/Mono3DRefer/'
  train_split: 'train'
  val_split: 'val'
  test_split: 'test'
  batch_size: 10
  use_3d_center: True
  bbox2d_type: 'anno'
  meanshape: False
  clip_2d: False

  aug_pd: True
  aug_crop: True

  random_flip: 0.5
  random_crop: 0.5
  scale: 0.05
  shift: 0.05

model_name: 'mono3dvg'

model:
  num_classes: 9
  return_intermediate_dec: True
  device: 'cuda'

  # Backbone
  backbone: 'resnet50'
  train_backbone: True
  num_feature_levels: 4
  dilation: False
  position_embedding: 'sine'  # 'sine' or 'learned'
  masks: False

  # Depth predictor
  mode: LID
  num_depth_bins: 80
  depth_min: 1e-3
  depth_max: 60.0

  # Transformer
  with_box_refine: True
  two_stage: False
  init_box: False
  enc_layers: 3
  dec_layers: 1
  hidden_dim: 256
  dim_feedforward: 256
  dropout: 0.1
  nheads: 8
  num_queries: 1
  enc_n_points: 4
  dec_n_points: 4
  freeze_text_encoder: True

  # Loss
  aux_loss: False

  # Loss coefficients
  cls_loss_coef: 2
  focal_alpha: 0.25

  bbox_loss_coef: 5
  giou_loss_coef: 2
  3dcenter_loss_coef: 10
  dim_loss_coef: 1
  angle_loss_coef: 1
  depth_loss_coef: 1
  depth_map_loss_coef: 1

  # Matcher
  set_cost_class: 2
  set_cost_bbox: 5
  set_cost_giou: 2
  set_cost_3dcenter: 10


optimizer:
  type: 'adamw'
  lr: 0.0001
  weight_decay: 0.0001


lr_scheduler:
  type: 'step'  # 'step' or 'cos'
  warmup: True  # 5 epoches, cosine warmup, init_lir=0.00001 in default
  decay_rate: 0.1
  decay_list: [40]


trainer:
  max_epoch: 60
  gpu_ids: '1'
  detr_model: 'checkpoint_best_MonoDETR.pth'
  save_frequency: 1    # checkpoint save interval (in epoch)
  resume_model: False
  pretrain_model: None
  save_path: 'outputs/'

tester:
  type: *dataset_type
  checkpoint: 195  # the start ckpt epoch for 'all'
  threshold: 0.0  # confidence filter
  topk: 1
  pretrain_model: 'checkpoint_best.pth'
